dist: bionic
language: node_js
node_js:
  - "lts/erbium"
install:
  - yarn
jobs:
  include:
    - stage: deploy
      if: branch = develop
      script:
        - yarn install
        - git remote set-url origin https://$GITHUB_TOKEN@github.com/0xGG/crossnote.git
        - CI= yarn deploy-gh-pages
notifications:
  email:
    on_success: never
    on_failure: change
